App\Entity\Envio:
    type: entity
    table: Envio
    oneToMany:
        orden:
            targetEntity: App\Entity\EnviosPorOrden
            mappedBy: envio
    id:
        id:
            type: guid
            id: true
            generate:
                strategy: UUID
    fields: 
            tipo:
                type: string
                length: 255
            precio:
                type: float
            descripcion: 
                type: string
                length: 255