App\Entity\EnviosPorOrden:
    type: entity
    table: EnviosPorOrden
    manyToOne:
        orden:
            targetEntity: App\Entity\Orden
            inversedBy: envios
            joinColumn:
                name: orden_id
                referencedColumnName: id   
                
        envio:
            targetEntity: App\Entity\Envio
            inversedBy: orden
            joinColumn: 
                name: envio_id
                referencedColumnName: id   
        
    id:
        id:
            type: guid
            id: true
            generate:
                strategy: UUID
    fields: 
        
            cantidad:
                type: float
            subtotal:
                type: float
            