App\Entity\ServiciosPorOrden:
    type: entity
    table: ServiciosPorOrden
    manyToOne:
        orden:
            targetEntity: App\Entity\Orden
            inversedBy: servicios
            joinColumn:
                name: orden_id
                referencedColumnName: id   
                
        servicio:
            targetEntity: App\Entity\Servicio
            inversedBy: orden
            joinColumn: 
                name: servicio_id
                referencedColumnName: id   
            
        
    id:
        id:
            type: guid
            id: true
            generate:
                strategy: UUID
    fields: 
        
            cantidad:
                type: float
            subtotal:
                type: float
            